### PR TITLE
bot: fix ordering issues in reply processing

### LINKED ISSUE #131: Scrollback module can violate causality
```
<ek> 2010-2016
<^> -6
```

Scrollback module sees:
```
<^> -6
<ek> 2010-2016
```

This is obviously a violation of the space-time continuum and should be fixed quickly

### PR DESCRIPTION
**Pull request by euank**
Fixes #131 

cc @LinuxMercedes @brhoades 

Testing done:

```
22:19:30 <me> 1+1
22:19:30 <seubot> 2
22:19:32 <me> !testscrollback 2,1
22:19:33 <seubot>  "<me> 1+1\n<seubot> 2"
```

### CODE REVIEW

**Comment by brhoades** [comment]
Where is the selfMessage hook used? Doesn't this need to be hooked into sayTo somewhere?

**Comment by LinuxMercedes** [comment]
Looks good to me--are you going to hook it into `reply` or `sayTo`?

**Comment by LinuxMercedes** [comment]
This is a lot better than a damn priority queue, but it's putting poor Computer Science students out of work by outsourcing their algorithms knowledge to some giant software library. :-1:

**Comment by euank** [comment]
@brhoades it's coming from the client itself right before it speaks here https://node-irc.readthedocs.io/en/latest/API.html#%27selfMessage%27

That's not some voodoo I cooked up, it's also unrelated to the actual fix (I coulda nextTick'd the thing i had before as well). It's just a refactor that makes things a little cleaner.

**Comment by LinuxMercedes** [comment]
Ahh, that's why 'selfMessage' didn't show up in a git grep (and no way in hell am I waiting for grep -R over node_modules...).

**Comment by LinuxMercedes** [comment]
Okay, I have one concern about this. What happens in the following situation: suppose we get two messages, `message1` and `message2`, and two modules, `mod1`, which will reply to `message1`, and `mod2`, which works like the scrollback module does.

```
callModuleFn(msg, message1) // triggers mod1 and mod2
  -> mod1.onmsg(message1)
    -> reply(bar)
      -> bot.client.say(bar)
        -> bot.client.emit(selfMessage)  // onpmsay deferred to nextTick
  -> mod2.onmsg(message1) // mod2.onmsg records "message1"
    -> ...
```
So far, so good. However, at this point, is it possible that the following happens:
```
callModuleFn(msg, message2)
  -> mod1.onmsg(message2)
    -> ...
  -> mod2.onmsg(message2) // mod2 records "message2"
    -> ...
callModuleFn(pmsay, bar) // From nextTick deferral
  -> mod2.onpmsay(bar) // mod2.onpmsay is triggered and records "bar"
    -> ...
```
Is this possible, and is it a problem? (Arguably, in this situation, `message2` was received before `bar` was transmitted, so this is a reasonable state of affairs.)

I can't tell what happens based on Node's docs. Maybe this is relevant:
"Note: the next tick queue is completely drained on each pass of the event loop before additional I/O is processed." [source](https://nodejs.org/api/process.html#process_process_nexttick_callback_args)

**Comment by euank** [comment]
I don't think that's possible @LinuxMercedes. I can't remember if we sorted this out on irc or not.

If this LGTY I'll merge.

**Comment by LinuxMercedes** [comment]
@euank I don't think we did, and I'd be interested in talking about it. 

But I'm not worried at all since if that were to be a bug, it would probably only be triggerable in cases where there is a lot of input to the bot all at once, which seems unlikely.

**Pull request merged**
