### PR TITLE
Add support for regex command matching

### PR DESCRIPTION
**Pull request by LinuxMercedes**
I am not sure if I hacked up the module manager right, but this seems to work based on my testing.

### CODE REVIEW

**Comment by euank** [comment]
LGTM. Mind rebasing and squashing a bit before i merge?

**Comment by LinuxMercedes** [comment]
Not at all. I'm going to add some shit to the test module too. 

One feature this lacks that might be nice is an optional argument to the command function saying which regex matched. I don't know if that's already done, though.

**Comment by LinuxMercedes** [comment]
And that should add the last feature I want from this.

**Comment by euank** [comment]
Nice, thanks!

**Pull request merged**
