### PR TITLE
Add raw twitter posting

### PR DESCRIPTION
**Pull request by LinuxMercedes**
My part in fighting the just cyberwar against ISIS.

### CODE REVIEW

**Comment by gmackie** [comment]
#fuckISIS #america :shipit

**Comment by LinuxMercedes** [comment]
Note: This code is really, really bad and should either be removed in the future or fixed to do any sort of reasonable error checking.

**Comment by euank** [comment]
Dude, commandtree was made exactly for this usecase.

**Comment by LinuxMercedes** [comment]
Oh, yeah, I vaguely remembered something meant for this use case. I'll re-do it right if we decide to keep it in. Even if we don't, I'll probably port the media uploading stuff to !quo with a regex or something, if that seems like not the worst idea.

**Pull request merged**
