### PR TITLE
Ensuring only nice things

### PR DESCRIPTION
**Pull request by ForLnex**

### CODE REVIEW

**Comment by cbgbt** [comment]
You're a bad man

**Comment by euank** [comment]
He is saving us all, @cbgbt. No pony for you.

**Comment by cbgbt** [comment]
I've been afk for a day or so. Is it bad?

**Comment by LinuxMercedes** [comment]
We've apparently not gotten past the novelty of !dumbcommand add explode 
"!exec node bot.js; yes '!explode'"

**Comment by gmackie** [comment]
to be fair, I still giggle reading the word "butts"

**Comment by LinuxMercedes** [comment]
and that is why 'butt stuff' is in the topic now

**Comment by drusepth** [comment]
butt stuff

**Pull request merged**
